export const USER_DATA = 'USER_DATA';
export const ADD_CART_PRODUCTS = 'ADD_CART_PRODUCTS';
export const REMOVE_CART_PRODUCTS = ' REMOVE_CART_PRODUCTS';
export const INCREASE_CART = 'INCREASE_CART';
export const DECREASE_CART = 'DECREASE_CART';
export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
export const REMOVE_FROM_WISHLIST = 'REMOVE_FROM_WISHLIST';

export const USER_ID = 'USER_ID';
export const GET_PRODUCTS = 'GET_PRODUCTS';

export const SET_ADDRESS = 'SET_ADDRESS';
export const DELETE_ADDRESS = 'DELETE_ADDRESS';
export const EDIT_ADDRESS = ' EDIT_ADDRESS';
export const SET_SELECTED_ADDRESS = 'SET_SELECTED_ADDRESS';
export const SET_DELIVERY_SLOT = 'SET_DELIVERY_SLOT';
export const SET_PAYMENT = 'SET_PAYMENT';

export const SET_CART_BILL_DETAILS = 'SET_CART_BILL_DETAILS';
